#!/usr/bin/env bash
#
# pipeline.sh — Download NOAA Storm Events data and convert storm locations to GeoParquet.
#
# Usage:   bash pipeline.sh [YEAR]
# Example: bash pipeline.sh 2024
#
# Requires: bash, curl, ogr2ogr (GDAL with Parquet support)
#
# NOAA currently publishes Storm Events as monthly CSV files. This script:
#   1. downloads monthly details and locations files for a given year
#   2. combines each set into annual CSVs
#   3. converts the locations CSV into GeoParquet using lon/lat geometry
#
# The data/ directory is generated by the script and should not be committed.

set -euo pipefail

# -----------------------------------------------------------------------------
# Config
# -----------------------------------------------------------------------------

# Year to pull. Override by passing a year as the first argument.
YEAR="${1:-2024}"

# NOAA monthly Storm Events archive for the selected year.
BASE_URL="https://www.ncei.noaa.gov/data/storm-events/access/original/${YEAR}"

RAW_DIR="data/raw/${YEAR}"
PROCESSED_DIR="data/processed"

# Annual CSV outputs built from the monthly NOAA files.
COMBINED_DETAILS_CSV="${RAW_DIR}/storms_${YEAR}_details.csv"
COMBINED_LOCATIONS_CSV="${RAW_DIR}/storms_${YEAR}_locations.csv"

# Final spatial output.
OUT_PARQUET="${PROCESSED_DIR}/storms_${YEAR}.parquet"

# -----------------------------------------------------------------------------
# Step 1: Set up directories
# -----------------------------------------------------------------------------

echo "[1/4] Setting up directories"

mkdir -p "$RAW_DIR" "$PROCESSED_DIR"

# -----------------------------------------------------------------------------
# Step 2: Download monthly details and locations files
# -----------------------------------------------------------------------------

echo "[2/4] Downloading monthly Storm Events detail and location files"

curl -L --fail "$BASE_URL/" \
  | grep -o 'StormEvents_\(details\|locations\)_[^"]*\.csv' \
  | sort -u \
  | while read -r FILE_NAME; do
      OUT_FILE="${RAW_DIR}/${FILE_NAME}"

      if [ -f "$OUT_FILE" ]; then
        echo "  Skipping existing file: $FILE_NAME"
      else
        echo "  Downloading: $FILE_NAME"
        curl -L --fail -o "$OUT_FILE" "${BASE_URL}/${FILE_NAME}"
      fi
    done

# -----------------------------------------------------------------------------
# Step 3: Combine monthly CSV files into annual CSV files
# -----------------------------------------------------------------------------

echo "[3/4] Combining monthly CSV files"

if [ -f "$COMBINED_DETAILS_CSV" ] && [ -f "$COMBINED_LOCATIONS_CSV" ]; then
    echo "  Combined CSVs already exist"
else
    FIRST_DETAILS=$(ls "$RAW_DIR"/StormEvents_details_*.csv | head -n 1)
    head -n 1 "$FIRST_DETAILS" > "$COMBINED_DETAILS_CSV"

    for FILE in "$RAW_DIR"/StormEvents_details_*.csv; do
        echo "  Adding details: $(basename "$FILE")"
        tail -n +2 "$FILE" >> "$COMBINED_DETAILS_CSV"
    done

    FIRST_LOCATIONS=$(ls "$RAW_DIR"/StormEvents_locations_*.csv | head -n 1)
    head -n 1 "$FIRST_LOCATIONS" > "$COMBINED_LOCATIONS_CSV"

    for FILE in "$RAW_DIR"/StormEvents_locations_*.csv; do
        echo "  Adding locations: $(basename "$FILE")"
        tail -n +2 "$FILE" >> "$COMBINED_LOCATIONS_CSV"
    done
fi

# -----------------------------------------------------------------------------
# Step 4: Convert locations CSV to GeoParquet
# -----------------------------------------------------------------------------

echo "[4/4] Converting locations to GeoParquet"

if [ -f "$OUT_PARQUET" ]; then
    echo "  Output already exists: $OUT_PARQUET"
else
    # The locations table contains lon/lat columns. These are used to build
    # point geometry in WGS 84 so the output opens as a spatial layer in QGIS.
    ogr2ogr \
      -f Parquet "$OUT_PARQUET" "$COMBINED_LOCATIONS_CSV" \
      -oo X_POSSIBLE_NAMES=lon \
      -oo Y_POSSIBLE_NAMES=lat \
      -a_srs EPSG:4326

    echo "  Created: $OUT_PARQUET"
fi

echo "Done. Output: ${OUT_PARQUET}"
echo "Open it in QGIS or query it with DuckDB:"
echo "  duckdb -c \"SELECT COUNT(*) FROM read_parquet('${OUT_PARQUET}');\""
